//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_4333
{
    using System;
    using System.Collections.Generic;
    
    public partial class isrpo2
    {
        public string IdServices { get; set; }
        public string NameServices { get; set; }
        public string TypeOfService { get; set; }
        public string CodeService { get; set; }
        public string Cost { get; set; }
    }
}
